// Sample data for theMenu diner app — Japanese-forward
// Deterministic ids drive the gradient engine.

const INGREDIENTS = {
  shiitake: {
    id: 'shiitake',
    name: 'Shiitake',
    aliases: ['Black forest mushroom', 'Donko'],
    jp: '椎茸',
    category: 'Fungi',
    origin: 'East Asia',
    tagline: 'Umami-dense forest mushroom, meaty when braised.',
    description: 'A lignicolous mushroom cultivated on oak logs since the Song dynasty. Prized in Japanese cooking for its deep glutamate content — the backbone of dashi when dried. Fresh shiitake are tender and woodsy; dried (donko) are concentrated and chewy.',
    commonIn: ['Dashi', 'Chawanmushi', 'Nimono'],
    gradient: ['oklch(0.38 0.04 60)', 'oklch(0.22 0.02 30)'],
  },
  nori: {
    id: 'nori',
    name: 'Nori',
    aliases: ['Laver'],
    jp: '海苔',
    category: 'Sea vegetable',
    origin: 'Japan, Korea',
    tagline: 'Toasted seaweed — crisp, briny, iron-dark.',
    description: 'Edible red algae of the genus Pyropia, cultivated on nets in coastal shallows then pressed into thin sheets and toasted. Shattering crisp when dry; goes supple with broth. Common allergen via iodine — rare but possible.',
    commonIn: ['Maki', 'Ramen', 'Onigiri'],
    gradient: ['oklch(0.38 0.05 160)', 'oklch(0.18 0.03 180)'],
  },
  miso: {
    id: 'miso',
    name: 'Miso (red)',
    aliases: ['Aka-miso'],
    jp: '赤味噌',
    category: 'Fermented',
    origin: 'Japan',
    tagline: 'Aged soybean paste — savory, salty, slightly sweet.',
    description: 'Soybeans and rice koji aged for months to years in cedar. Red miso is aged longest; its proteins break into a dark, assertive paste. Contains soy — relevant for allergen filtering.',
    commonIn: ['Miso soup', 'Ramen broth', 'Glazes'],
    gradient: ['oklch(0.48 0.12 45)', 'oklch(0.28 0.08 30)'],
    allergens: ['soy'],
  },
  tofu: {
    id: 'tofu',
    name: 'Silken tofu',
    aliases: ['Kinugoshi'],
    jp: '絹ごし豆腐',
    category: 'Soy',
    origin: 'China, Japan',
    tagline: 'Coagulated soy milk, custard-soft.',
    description: 'Silken tofu is set directly in its packaging — no pressing — giving a delicate, pudding-like texture that collapses into broth. A staple protein across East Asia.',
    commonIn: ['Miso soup', 'Hiyayakko', 'Mapo tofu'],
    gradient: ['oklch(0.92 0.03 90)', 'oklch(0.75 0.04 80)'],
    allergens: ['soy'],
  },
  scallion: {
    id: 'scallion',
    name: 'Scallion',
    aliases: ['Negi', 'Green onion'],
    jp: '葱',
    category: 'Allium',
    origin: 'Asia',
    tagline: 'Sharp when raw, sweet when wilted.',
    description: 'Young Allium fistulosum harvested before the bulb swells. The white part is pungent and onion-like; the green is grassy and mild. Cut thinly on the bias for ramen.',
    commonIn: ['Ramen', 'Gyoza', 'Donburi'],
    gradient: ['oklch(0.78 0.14 140)', 'oklch(0.55 0.15 150)'],
  },
  pork_belly: {
    id: 'pork_belly',
    name: 'Chashu pork belly',
    aliases: ['Chāshū', 'Braised pork'],
    jp: 'チャーシュー',
    category: 'Meat',
    origin: 'Japan (via China)',
    tagline: 'Rolled pork belly braised in soy, mirin, sake.',
    description: 'Despite the name (from Cantonese char siu), Japanese chashu is braised, not roasted. The belly is rolled, tied, and simmered until fork-tender in a dark broth of shoyu, mirin, sake and aromatics.',
    commonIn: ['Tonkotsu ramen', 'Shoyu ramen', 'Donburi'],
    gradient: ['oklch(0.55 0.11 35)', 'oklch(0.32 0.07 25)'],
  },
  egg: {
    id: 'egg',
    name: 'Ajitama egg',
    aliases: ['Ajitsuke tamago', 'Soft-boiled egg'],
    jp: '味付け玉子',
    category: 'Egg',
    origin: 'Japan',
    tagline: 'Soft-boiled egg marinated in soy and mirin.',
    description: 'Boiled six minutes to set the white while keeping a liquid center, then marinated overnight in shoyu, mirin and sake. The yolk thickens into something like custard.',
    commonIn: ['Ramen', 'Donburi'],
    gradient: ['oklch(0.88 0.12 85)', 'oklch(0.62 0.16 65)'],
    allergens: ['egg'],
  },
  wheat_noodle: {
    id: 'wheat_noodle',
    name: 'Ramen noodle',
    aliases: ['Chūkamen'],
    jp: '中華麺',
    category: 'Grain',
    origin: 'Japan (via China)',
    tagline: 'Alkaline wheat noodle — springy, yellow.',
    description: 'Wheat flour cut with kansui (alkaline mineral water), which gives ramen noodles their yellow tint and distinctive chew. Thin and straight for tonkotsu; thicker and wavy for miso.',
    commonIn: ['Ramen'],
    gradient: ['oklch(0.85 0.10 92)', 'oklch(0.65 0.12 85)'],
    allergens: ['wheat'],
  },
  rice: {
    id: 'rice',
    name: 'Koshihikari rice',
    aliases: ['Short-grain rice'],
    jp: 'コシヒカリ',
    category: 'Grain',
    origin: 'Niigata, Japan',
    tagline: 'Glossy short-grain rice — slightly sweet, pleasantly sticky.',
    description: 'The most widely planted rice cultivar in Japan, bred in 1956. High in amylopectin, so it clumps just enough to be picked up with chopsticks without being mushy.',
    commonIn: ['Sushi', 'Donburi', 'Onigiri'],
    gradient: ['oklch(0.94 0.02 90)', 'oklch(0.82 0.03 85)'],
  },
  salmon: {
    id: 'salmon',
    name: 'Sake (salmon)',
    aliases: ['Atlantic salmon', 'Sake'],
    jp: '鮭',
    category: 'Fish',
    origin: 'North Atlantic / farmed',
    tagline: 'Fatty, coral-pink fish with buttery texture.',
    description: 'Oncorhynchus / Salmo species, aquacultured for sushi grade to ensure parasite-free flesh. High in omega-3 lipids and marbled with visible fat lines.',
    commonIn: ['Nigiri', 'Sashimi', 'Poke'],
    gradient: ['oklch(0.75 0.15 35)', 'oklch(0.52 0.16 25)'],
    allergens: ['fish'],
  },
  tuna: {
    id: 'tuna',
    name: 'Maguro (bluefin)',
    aliases: ['Tuna', 'Akami'],
    jp: '鮪',
    category: 'Fish',
    origin: 'Pacific',
    tagline: 'Deep-red, lean, iron-mineral fish.',
    description: 'Pacific bluefin tuna, graded by cut: akami (lean, red), chutoro (medium-fatty), otoro (fatty belly). This kitchen uses akami from rod-and-line fisheries.',
    commonIn: ['Nigiri', 'Sashimi', 'Maki'],
    gradient: ['oklch(0.48 0.17 25)', 'oklch(0.28 0.14 20)'],
    allergens: ['fish'],
  },
  wasabi: {
    id: 'wasabi',
    name: 'Fresh wasabi',
    aliases: ['Japanese horseradish'],
    jp: '山葵',
    category: 'Root',
    origin: 'Japan',
    tagline: 'Grated rhizome with a bright, nasal heat.',
    description: 'Wasabia japonica grown in shallow mountain streams. True wasabi is rare; most supermarket "wasabi" is horseradish dyed green. Heat dissipates within minutes of grating.',
    commonIn: ['Sushi', 'Sashimi'],
    gradient: ['oklch(0.72 0.16 135)', 'oklch(0.48 0.14 140)'],
  },
  ginger: {
    id: 'ginger',
    name: 'Pickled ginger',
    aliases: ['Gari'],
    jp: 'ガリ',
    category: 'Root',
    origin: 'Asia',
    tagline: 'Thin slices of young ginger in sweet vinegar.',
    description: 'Young ginger root sliced paper-thin and brined in sweetened rice vinegar. Served to cleanse the palate between pieces of sushi, not to be piled on top.',
    commonIn: ['Sushi'],
    gradient: ['oklch(0.92 0.05 20)', 'oklch(0.78 0.08 15)'],
  },
  bonito: {
    id: 'bonito',
    name: 'Katsuobushi',
    aliases: ['Bonito flakes', 'Skipjack'],
    jp: '鰹節',
    category: 'Fish',
    origin: 'Japan',
    tagline: 'Smoked, fermented, shaved tuna.',
    description: 'Skipjack tuna simmered, smoked, sun-dried and fermented with Aspergillus mold until hard as wood — then shaved into translucent flakes. One of the two pillars of dashi.',
    commonIn: ['Dashi', 'Okonomiyaki', 'Hiyayakko'],
    gradient: ['oklch(0.68 0.09 50)', 'oklch(0.42 0.08 40)'],
    allergens: ['fish'],
  },
  kombu: {
    id: 'kombu',
    name: 'Kombu',
    aliases: ['Dashima', 'Kelp'],
    jp: '昆布',
    category: 'Sea vegetable',
    origin: 'Hokkaidō',
    tagline: 'Cold-water kelp, dried — pure glutamate.',
    description: 'Saccharina japonica harvested off Hokkaidō, sun-dried into leathery strips. Steeped in cold water, it releases free glutamate — the original umami source identified by Ikeda in 1908.',
    commonIn: ['Dashi'],
    gradient: ['oklch(0.32 0.05 160)', 'oklch(0.18 0.03 170)'],
  },
  sesame: {
    id: 'sesame',
    name: 'Sesame seeds',
    aliases: ['Goma'],
    jp: '胡麻',
    category: 'Seed',
    origin: 'Africa / Asia',
    tagline: 'Toasted seeds — nutty, with visible oil.',
    description: 'Sesamum indicum seeds, toasted until they pop and deepen to a golden brown. White and black varieties differ mainly in seed coat; both carry a high oil content.',
    commonIn: ['Gomae', 'Ramen toppings'],
    gradient: ['oklch(0.72 0.08 85)', 'oklch(0.48 0.07 70)'],
    allergens: ['sesame'],
  },
  cucumber: {
    id: 'cucumber',
    name: 'Japanese cucumber',
    aliases: ['Kyūri'],
    jp: '胡瓜',
    category: 'Vegetable',
    origin: 'Japan',
    tagline: 'Thin-skinned, nearly seedless, crisp.',
    description: 'A ridged, slim cultivar of Cucumis sativus bred for eating fresh or pickling. Smaller seeds and thinner skin than Western cucumbers.',
    commonIn: ['Sunomono', 'Maki', 'Salads'],
    gradient: ['oklch(0.85 0.12 140)', 'oklch(0.6 0.14 150)'],
  },
  avocado: {
    id: 'avocado',
    name: 'Avocado',
    aliases: ['Hass'],
    jp: 'アボカド',
    category: 'Fruit',
    origin: 'Mexico',
    tagline: 'Buttery green fruit — creamy, mild.',
    description: 'Persea americana. Not traditionally Japanese, but a standard sushi-bar addition in the diaspora since the 1970s for its fatty texture standing in for toro.',
    commonIn: ['Maki'],
    gradient: ['oklch(0.72 0.13 125)', 'oklch(0.48 0.12 130)'],
  },
  soy_sauce: {
    id: 'soy_sauce',
    name: 'Shoyu',
    aliases: ['Soy sauce', 'Koikuchi'],
    jp: '醤油',
    category: 'Condiment',
    origin: 'Japan',
    tagline: 'Fermented soy, wheat, salt, koji.',
    description: 'Soybeans and roasted wheat inoculated with Aspergillus oryzae, brined, and fermented six months to two years. Koikuchi ("dark") is the default; usukuchi is lighter and saltier.',
    commonIn: ['Nearly everything'],
    gradient: ['oklch(0.32 0.07 55)', 'oklch(0.18 0.05 40)'],
    allergens: ['soy', 'wheat'],
  },
  bamboo: {
    id: 'bamboo',
    name: 'Menma',
    aliases: ['Bamboo shoots', 'Lactic-fermented'],
    jp: 'メンマ',
    category: 'Vegetable',
    origin: 'Taiwan / Japan',
    tagline: 'Fermented, dried bamboo shoots.',
    description: 'Young Phyllostachys bamboo shoots lactic-fermented, dried, then rehydrated and seasoned. Chewy, slightly tart, and a standard ramen topping.',
    commonIn: ['Ramen'],
    gradient: ['oklch(0.75 0.08 85)', 'oklch(0.52 0.08 70)'],
  },
};

// Dishes — each has ingredient ids, nutrition, price
const DISHES = [
  {
    id: 'tonkotsu',
    name: 'Tonkotsu Ramen',
    jp: '豚骨ラーメン',
    section: 'Ramen',
    tagline: 'Twelve-hour pork bone broth, chashu, ajitama.',
    description: 'Our signature. Pork femurs and trotters boiled at a hard roll for twelve hours until the marrow emulsifies into an opaque, collagen-heavy broth. Finished with a dark tare, a coil of thin straight noodles, and classic toppings.',
    price: 18.5,
    ingredients: ['wheat_noodle', 'pork_belly', 'egg', 'scallion', 'nori', 'bamboo', 'soy_sauce'],
    nutrition: { cal: 720, fat: 32, protein: 38, carbs: 64 },
    notes: 'Contains wheat, soy, egg. Spicy upgrade available.',
    spice: 1,
    chefPick: true,
  },
  {
    id: 'miso_ramen',
    name: 'Sapporo Miso Ramen',
    jp: '札幌味噌ラーメン',
    section: 'Ramen',
    tagline: 'Red miso, corn, butter, chashu, wavy noodle.',
    description: 'A bowl in the Hokkaidō tradition. Chicken-pork base tightened with aged red miso, topped with sweet corn, a slow-melting pat of cultured butter, bean sprouts, and charred scallion.',
    price: 17.0,
    ingredients: ['wheat_noodle', 'miso', 'pork_belly', 'scallion', 'bamboo', 'sesame'],
    nutrition: { cal: 680, fat: 28, protein: 34, carbs: 72 },
    notes: 'Contains wheat, soy, sesame, dairy.',
    spice: 1,
  },
  {
    id: 'veg_ramen',
    name: 'Kinoko Shōyu Ramen',
    jp: '茸醤油ラーメン',
    section: 'Ramen',
    tagline: 'Vegetable dashi, four mushrooms, silken tofu.',
    description: 'Vegetarian. A dashi of kombu and four dried mushrooms, pulled with shoyu tare. Topped with roasted shiitake, enoki, silken tofu cubes, and sesame.',
    price: 16.0,
    ingredients: ['wheat_noodle', 'shiitake', 'tofu', 'kombu', 'soy_sauce', 'scallion', 'sesame'],
    nutrition: { cal: 520, fat: 18, protein: 22, carbs: 68 },
    notes: 'Vegetarian. Contains wheat, soy, sesame.',
    dietary: ['vegetarian'],
  },
  {
    id: 'salmon_nigiri',
    name: 'Sake Nigiri',
    jp: '鮭握り',
    section: 'Sushi',
    tagline: 'Two pieces — Atlantic salmon, hand-pressed.',
    description: 'Two pieces. Ora King salmon from New Zealand, sliced against the grain at 6mm, hand-pressed onto koshihikari rice seasoned with our house vinegar blend.',
    price: 9.0,
    ingredients: ['salmon', 'rice', 'wasabi'],
    nutrition: { cal: 180, fat: 6, protein: 14, carbs: 22 },
    notes: 'Contains fish.',
    dietary: ['gluten-free-possible'],
  },
  {
    id: 'tuna_nigiri',
    name: 'Maguro Nigiri',
    jp: '鮪握り',
    section: 'Sushi',
    tagline: 'Two pieces — akami bluefin tuna.',
    description: 'Two pieces. Pacific bluefin akami, aged two days at 0°C to deepen color and break down sinew. A dab of wasabi between fish and rice.',
    price: 11.0,
    ingredients: ['tuna', 'rice', 'wasabi'],
    nutrition: { cal: 170, fat: 3, protein: 18, carbs: 22 },
    notes: 'Contains fish.',
    dietary: ['gluten-free-possible'],
  },
  {
    id: 'hosomaki',
    name: 'Kappa Maki',
    jp: '河童巻き',
    section: 'Sushi',
    tagline: 'Cucumber, rice, nori — six pieces.',
    description: 'Six pieces. The simplest maki: a single stick of kyūri cucumber wrapped in rice and nori, cut into bite-sized rounds. Named after the cucumber-loving river imp.',
    price: 7.0,
    ingredients: ['cucumber', 'rice', 'nori', 'sesame'],
    nutrition: { cal: 220, fat: 2, protein: 4, carbs: 46 },
    notes: 'Contains sesame.',
    dietary: ['vegan'],
  },
  {
    id: 'avocado_maki',
    name: 'Avocado Maki',
    jp: 'アボカド巻き',
    section: 'Sushi',
    tagline: 'Hass avocado, rice, nori — six pieces.',
    description: 'Six pieces. Ripe Hass avocado sliced thin and rolled with rice and nori. A study in fat and salt, nothing more.',
    price: 8.0,
    ingredients: ['avocado', 'rice', 'nori', 'sesame'],
    nutrition: { cal: 260, fat: 11, protein: 4, carbs: 38 },
    notes: 'Contains sesame.',
    dietary: ['vegan'],
  },
  {
    id: 'miso_soup',
    name: 'Miso Shiru',
    jp: '味噌汁',
    section: 'Small plates',
    tagline: 'Dashi, red miso, tofu, scallion.',
    description: 'Kombu-bonito dashi seasoned with red miso just before serving — never boiled, to preserve the living cultures. Silken tofu, wakame, and a shower of scallion.',
    price: 4.5,
    ingredients: ['miso', 'tofu', 'kombu', 'bonito', 'scallion'],
    nutrition: { cal: 85, fat: 3, protein: 6, carbs: 7 },
    notes: 'Contains soy, fish.',
  },
  {
    id: 'sunomono',
    name: 'Sunomono',
    jp: '酢の物',
    section: 'Small plates',
    tagline: 'Cucumber, rice vinegar, sesame, ginger.',
    description: 'Paper-thin cucumber salted and pressed, then dressed in sweet rice vinegar. Topped with toasted sesame and a coil of pickled ginger.',
    price: 6.0,
    ingredients: ['cucumber', 'sesame', 'ginger'],
    nutrition: { cal: 60, fat: 2, protein: 2, carbs: 10 },
    notes: 'Contains sesame.',
    dietary: ['vegan'],
  },
  {
    id: 'gomae',
    name: 'Horenso Gomaae',
    jp: '胡麻和え',
    section: 'Small plates',
    tagline: 'Blanched spinach, black sesame paste.',
    description: 'Spinach blanched, shocked, and wrung dry, then dressed with a black sesame paste loosened with shoyu, mirin and a whisper of sugar.',
    price: 7.5,
    ingredients: ['sesame', 'soy_sauce'],
    nutrition: { cal: 140, fat: 8, protein: 5, carbs: 12 },
    notes: 'Contains sesame, soy, wheat.',
    dietary: ['vegan'],
  },
];

const RESTAURANTS = [
  {
    id: 'tsubaki',
    name: 'Tsubaki',
    subtitle: 'Izakaya & Ramen',
    neighborhood: 'Mission District',
    distance: '0.4 mi',
    rating: 4.8,
    priceLevel: '$$',
    tagline: 'Twelve-hour tonkotsu and sushi in equal measure.',
    hours: 'Open · closes 10pm',
    theme: 'editorial',
    cover: ['oklch(0.94 0.03 60)', 'oklch(0.78 0.08 40)'],
    accent: 'oklch(0.52 0.18 25)', // shu-iro
    established: 2014,
  },
  {
    id: 'hako',
    name: 'Hako Ramen Bar',
    subtitle: 'Counter ramen',
    neighborhood: 'Financial District',
    distance: '0.9 mi',
    rating: 4.6,
    priceLevel: '$$',
    tagline: 'Six stools, seven bowls, no reservations.',
    hours: 'Open · closes 9pm',
    theme: 'utility',
    cover: ['oklch(0.92 0.01 240)', 'oklch(0.72 0.02 250)'],
    accent: 'oklch(0.45 0.17 260)',
    established: 2021,
  },
  {
    id: 'komorebi',
    name: 'Komorebi',
    subtitle: 'Neighborhood kissaten',
    neighborhood: 'Hayes Valley',
    distance: '1.2 mi',
    rating: 4.7,
    priceLevel: '$',
    tagline: 'Curry rice, onigiri, and egg salad sandos.',
    hours: 'Open · closes 7pm',
    theme: 'soft',
    cover: ['oklch(0.94 0.05 80)', 'oklch(0.85 0.09 40)'],
    accent: 'oklch(0.62 0.14 40)',
    established: 2019,
  },
  {
    id: 'ao',
    name: 'Aoyagi',
    subtitle: 'Sushi counter',
    neighborhood: 'Japantown',
    distance: '1.8 mi',
    rating: 4.9,
    priceLevel: '$$$$',
    tagline: 'Omakase only. Eight seats.',
    hours: 'Two seatings — 6pm, 8:30pm',
    theme: 'editorial',
    cover: ['oklch(0.28 0.02 230)', 'oklch(0.14 0.02 240)'],
    accent: 'oklch(0.82 0.12 85)',
    established: 2008,
  },
];

const DIETARY_FILTERS = [
  { id: 'vegetarian', label: 'Vegetarian' },
  { id: 'vegan', label: 'Vegan' },
  { id: 'gluten-free', label: 'Gluten-free' },
  { id: 'pescatarian', label: 'Pescatarian' },
];

const ALLERGENS = [
  { id: 'wheat', label: 'Wheat / gluten' },
  { id: 'soy', label: 'Soy' },
  { id: 'egg', label: 'Egg' },
  { id: 'fish', label: 'Fish' },
  { id: 'shellfish', label: 'Shellfish' },
  { id: 'sesame', label: 'Sesame' },
  { id: 'peanut', label: 'Peanut' },
  { id: 'dairy', label: 'Dairy' },
];

Object.assign(window, {
  INGREDIENTS, DISHES, RESTAURANTS, DIETARY_FILTERS, ALLERGENS,
});
