#!/usr/bin/env node
// Regenerates docs/TASKLOGGING.md from every docs/goals/*/features/*/task-log.md.
// Dependency-free by design (see AGENTS.md / CLAUDE.md — no new top-level deps without being asked).

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, dirname, sep } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const docsDir = join(repoRoot, "docs");
const goalsDir = join(docsDir, "goals");
const outputFile = join(docsDir, "TASKLOGGING.md");
const sourceScript = "scripts/gen-tasklog.mjs";

const ENTRY_HEADER_RE = /^## (\d{4}-\d{2}-\d{2} \d{2}:\d{2}) — (.+)$/;
const COMMIT_RE = /^\*\*Commit:\*\*\s*(\S+)/;

function findTaskLogFiles() {
  const files = [];
  let goalDirs;
  try {
    goalDirs = readdirSync(goalsDir);
  } catch {
    return files;
  }
  for (const goal of goalDirs) {
    const featuresDir = join(goalsDir, goal, "features");
    let featureDirs;
    try {
      featureDirs = readdirSync(featuresDir);
    } catch {
      continue;
    }
    for (const feature of featureDirs) {
      const taskLogPath = join(featuresDir, feature, "task-log.md");
      try {
        if (statSync(taskLogPath).isFile()) {
          files.push({ goal, feature, path: taskLogPath });
        }
      } catch {
        // no task-log.md for this feature yet — skip
      }
    }
  }
  return files;
}

function parseTaskLog({ goal, feature, path }) {
  const content = readFileSync(path, "utf8");
  const lines = content.split(/\r\n|\n/);
  const entries = [];
  let current = null;

  function flush() {
    if (current) {
      current.summary = current.summaryLines.join("\n").trim();
      delete current.summaryLines;
      entries.push(current);
    }
  }

  for (const line of lines) {
    const headerMatch = line.match(ENTRY_HEADER_RE);
    if (headerMatch) {
      flush();
      current = {
        timestamp: headerMatch[1],
        title: headerMatch[2].trim(),
        commit: null,
        summaryLines: [],
        goal,
        feature,
        path
      };
      continue;
    }
    if (!current) continue;
    const commitMatch = line.match(COMMIT_RE);
    if (commitMatch && !current.commit) {
      current.commit = commitMatch[1];
      continue;
    }
    current.summaryLines.push(line);
  }
  flush();
  return entries;
}

function main() {
  const files = findTaskLogFiles();
  const allEntries = files.flatMap(parseTaskLog);

  allEntries.sort((a, b) => (a.timestamp < b.timestamp ? 1 : a.timestamp > b.timestamp ? -1 : 0));

  const lines = [];
  lines.push("# Task log (generated)");
  lines.push("");
  lines.push(
    `This file is generated by \`${sourceScript}\` (\`pnpm docs:tasklog\`) from every ` +
      "`docs/goals/*/features/*/task-log.md`. **Do not hand-edit this file** — edit the source " +
      "`task-log.md` for the relevant feature instead, then regenerate."
  );
  lines.push("");

  if (allEntries.length === 0) {
    lines.push("_No task-log entries found yet._");
  } else {
    for (const entry of allEntries) {
      const relPath = relative(docsDir, entry.path).split(sep).join("/");
      lines.push(`## ${entry.timestamp} — ${entry.title}`);
      lines.push("");
      const commitPart = entry.commit ? `**Commit:** ${entry.commit} · ` : "";
      lines.push(`${commitPart}[${entry.goal} / ${entry.feature}](./${relPath})`);
      if (entry.summary) {
        lines.push("");
        lines.push(entry.summary);
      }
      lines.push("");
    }
  }

  writeFileSync(outputFile, lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n");
  console.log(`Wrote ${relative(repoRoot, outputFile)} (${allEntries.length} entries from ${files.length} task-log.md files)`);
}

main();
